from ural.types import AnyUrlTarget

def fingerprint_url(url: str, unsplit: bool = ...) -> str: ...
def fingerprint_hostname(hostname: str) -> str: ...
def get_fingerprinted_hostname(
    url: AnyUrlTarget,
    infer_redirection: bool = True,
) -> str: ...
