from typing import List, Tuple

def safely_unquote_auth_item(string: str) -> str: ...
def safely_unquote_path(string: str) -> str: ...
def safely_unquote_query_item(string: str) -> str: ...
def safely_unquote_fragment(string: str) -> str: ...
def safely_unquote_qsl(qsl: List[Tuple[str, str]]) -> List[Tuple[str, str]]: ...
def safely_quote(string: str) -> str: ...