name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        include:
          # Current ubuntu
          # NOTE: py27 support was dropped by GitHub Actions...
          # - os: ubuntu-20.04
          #   python-version: "2.7"
          - os: ubuntu-20.04
            python-version: "3.5"
          - os: ubuntu-20.04
            python-version: "3.6"
          - os: ubuntu-20.04
            python-version: "3.7"
          - os: ubuntu-20.04
            python-version: "3.8"
          - os: ubuntu-20.04
            python-version: "3.9"

          # Mac
          - os: macos-latest
            python-version: "3.6"

          # Windows
          - os: windows-latest
            python-version: "3.6"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run linter & unit tests
        run: make
